configuration/index.md
examples/ansible/index.md
examples/gnmi-clients/gnmic/index.md
examples/gnmi-gateway/index.md
examples/golang/index.md
examples/index.md
examples/python/index.md
faq/index.md
index.md
misc-topics/index.md
models/index.md
protocols/index.md
telemetry/index.md

The `layout: page` is referencing a layout that doesn't exist. I think changing to `default` will fix the theme issue.

changing layout to default

---

_config.yml

changing theme to lanyon

---

_config.yml

messed up the theme syntax, should be remote_theme

---

configuration/index.md
examples/index.md
index.md
models/index.md
protocols/index.md

Added some intro words, moved some information around to appropriate folders, and added some links to orphaned content.

doc cleanup

---

configuration/index.md

Removing indentations for code snippets to fix rendering issue on gh-pages

configuration: remove indentation for code snippets

---

docs/configuration/index.md

@nandanarista provided a patch to address a typo in a config example ( #35 )
this creates the necessary PR to merge his patch.

merge nandan's fix from issue #35

---

docs/configuration/mtls.md
docs/configuration/security.md
docs/examples/gnmi-clients/arista-gnmi/index.md
docs/examples/gnmi-gateway/index.md

basically what it says on the tin. 
- split various examples up into code blocks to improve readability and consistency.
- tried to make sure that there aren't any lingering `./` invocations
- added output headers where appropriate
- misc. grammatical cleaning

misc. code block consistency cleanup

---

.github/workflows/main.yml

Just adding `gh-deploy` to auto  build the site when main is pushed

adding `gh-deploy` to actions

---

docs/examples/gnoi/gnoic/index.md
docs/examples/gnoi/grpcurl/index.md
docs/examples/index.md
mkdocs.yml

Adding gNOI examples using gNOIc and gRPCurl

issue#47 add gNOI examples using gNOIc and gRPCurl

---

docs/examples/gnoi/gnoic/index.md
docs/examples/gnoi/grpcurl/index.md
docs/examples/pyang/index.md
docs/examples/ygot/index.md

as noted on the tin.
@fredhsu i think we discussed this previously, but we should add a `markdownlint` check to pull requests.

misc linting cleanup

---

.github/workflows/lint.yml
.github/workflows/main.yml

Adding a stage for linting the markdown as part of the CI

Fred lint ci

---

.github/workflows/lint.yml
.github/workflows/main.yml

Removing overlapping / unnecessary steps in the CI pipeline

CI file cleanup

---

.github/workflows/stale.yml

i should have caught this earlier. this just adds a little more context to the notification emails that are sent.

adds useful stale notification messages

---

.github/workflows/stale.yml

adds a couple of closure messages to the bot operation.

added close-{issue,pr}-messages

---

docs/configuration/openconfig.md

- adds some documentation for notification timestamp modification
- addresses #38 
- minor updates to formatting per style guide

add gnmi timestamp notes

---

docs/videos/index.md

Adding new links to videos posted on youtube

adding new openconfig videos

---

docs/configuration/openconfig.md
docs/examples/restconf/curl.md

Fixed #110 and also added more description + changed the IPs to RFC5737 range

Issue110 update restconf example

---

docs/configuration/openconfig.md

added an example showing how to enable OC syslog messages

fix #115 add syslog messages to OC

---

docs/telemetry/adapters/ocprometheus/index.md

Regex101 link led to missing file vs regex101 site.

Minor fix on broken link

---

docs/examples/gnmi-clients/gnmic/index.md

Adding example for `/telemetry-system/subscriptions` under gnmi-clients > gnmic 
`docs/examples/gnmi-clients/gnmic/index.md`

adding example for telemetry-system
